### PR TITLE
Adding @Goredbird's work

### PR DESCRIPTION
**Pull request by Vic-ST**
Some of @GoRedbirds work

### CODE REVIEW

**Comment by ruu5cn** [comment]
The Jquery and javascript isn't working. Look at the github pages.

**Comment by Vic-ST** [comment]
Checking now......

**Comment by Vic-ST** [comment]
Now look!

**Comment by ruu5cn** [comment]
Can you send me the link?

**Comment by Vic-ST** [comment]
This it? https://github.com/Stores/Stores

**Pull request merged**
